#ifndef _DFGAP_COMMON_H
#define _DFGAP_COMMON_H
#include <sys/types.h>
#include <stdio.h>
#include "packet.h"

#define PACKET_MAXLEN		4000 		// 08-02-22 Paused for test if the buffer is overflowed by dirver
#define GFDATA_MAXLEN		PACKET_MAXLEN+sizeof(Packet_t)
#define MAX_CHANNEL_NUM	4		

#define SIDE_CLIENT		0
#define SIDE_SERVER		1

#define SIDE_INSIDE		0
#define SIDE_OUTSIDE	1

#define ALL "0.0.0.0"
#define SUC_INFO "<EFSFRAME><ERRORINFO><ERRORRESULT>0</ERRORRESULT><FUNCERROR></FUNCERROR></ERRORINFO></EFSFRAME>"
#define ERROR_INFO "<EFSFRAME><ERRORINFO><ERRORRESULT>1</ERRORRESULT><FUNCERROR>4</FUNCERROR></ERRORINFO></EFSFRAME>"
#define ERROR_INFO_IP "<EFSFRAME><ERRORINFO><ERRORRESULT>1</ERRORRESULT><FUNCERROR>1</FUNCERROR></ERRORINFO></EFSFRAME>"
#define SUC_RULE_INFO "<EFSFRAME><ERRORINFO><ERRORRESULT>0</ERRORRESULT><FUNCERROR></FUNCERROR></ERRORINFO></EFSFRAME>"
#define ERROR_INFO_MAC "<EFSFRAME><ERRORINFO><ERRORRESULT>1</ERRORRESULT><FUNCERROR>2</FUNCERROR></ERRORINFO></EFSFRAME>"
#define ERROR_RULE_INFO "<EFSFRAME><ERRORINFO><ERRORRESULT>1</ERRORRESULT><FUNCERROR>2</FUNCERROR></ERRORINFO></EFSFRAME>"
#define ERROR_RULE_INFO_EXIST "<EFSFRAME><ERRORINFO><ERRORRESULT>1</ERRORRESULT><FUNCERROR>1</FUNCERROR></ERRORINFO></EFSFRAME>"
#define ERROR_INFO_HOST "<EFSFRAME><ERRORINFO><ERRORRESULT>1</ERRORRESULT><FUNCERROR>3</FUNCERROR></ERRORINFO></EFSFRAME>"
#define ERROR_INFO_USEDHOST "<EFSFRAME><ERRORINFO><ERRORRESULT>1</ERRORRESULT><FUNCERROR>5</FUNCERROR></ERRORINFO></EFSFRAME>"

#ifndef MAX
#define MIN(a,b)	((a)<(b)?(a):(b))
#define MAX(a,b)	((a)>(b)?(a):(b))
#endif

extern void error (char *, ...);
extern void warn  (char *, ...);
extern void panic (char *, ...);
extern void disp  (char *, ...);

extern void SkipComment (FILE *fp);


#endif //_DFGAP_COMMON_H
